meetingscheduler/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('home/', include('scheduler.urls')),
    path('admin/', admin.site.urls),
]

scheduler/urls.py
from django.urls import path

from . import views

app_name = 'scheduler'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('bookslot/', views.book_slot, name='book_slot'),
    path('logout/', views.logout, name='logout'),
    path('createevent/', views.create_event, name='create_event'),
]

scheduler/models.py
from django.db import models

# Create your models here.


class User(models.Model):

    user_fname = models.CharField(max_length=80)
    user_lname = models.CharField(max_length=80)
    user_email = models.EmailField(unique=True)
    user_password = models.CharField(max_length=500)

    def user_mail(self):
        return self.user_email


class Bookings(models.Model):

    client_name = models.CharField(max_length=20)
    client_email = models.EmailField()
    slot_date = models.CharField(max_length=20)
    slot_time = models.CharField(max_length=20)
    slot_end_time = models.CharField(max_length=20)
    is_scheduled = models.BooleanField(default=False)

scheduler/forms.py
from django import forms

from .models import User


class SignupForm(forms.Form):
    fname = forms.CharField(label="First Name", max_length=50,required=True)
    lname = forms.CharField(label="Last Name", max_length=50,required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(label="New Password", max_length=10,
                               widget=forms.PasswordInput, required=True)
    repassword = forms.CharField(label="Re-type Password", max_length=10,
                                 widget=forms.PasswordInput, required=True)

    class Meta:
        model = User

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            match = User.objects.get(user_email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('This email address is already in use.')

    def clean_repassword(self):
        psw = self.cleaned_data.get('password')
        repsw = self.cleaned_data.get('repassword')
        if psw != repsw:
            raise forms.ValidationError("Password doesn't match!")
        return self.cleaned_data


class LoginForm(forms.Form):

    username = forms.CharField(label="Email/Username", max_length=50, required=True)
    password = forms.CharField(
        label="Password", max_length=10,
        widget=forms.PasswordInput, required=True
        )

    class Meta:
        model = User

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        try:
            user = User.objects.get(user_email=username)
            if user.user_password != password:
                raise forms.ValidationError("Sorry, wrong username or password !")
        except User.DoesNotExist:
                raise forms.ValidationError("Invalid Login")
        return self.cleaned_data

scheduler/views.py
import datetime
from datetime import timedelta
from django.http import HttpResponseRedirect
from django.shortcuts import render,redirect
from django.urls import reverse

import pytz
from googleapiclient.discovery import build
from httplib2 import Http
from oauth2client import file, client, tools

from .forms import SignupForm, LoginForm
from .models import User, Bookings

SCOPES = 'https://www.googleapis.com/auth/calendar'


def index(request):
    if 'user_id' in request.session:
        userid = request.session['user_id']
        user = User.objects.get(pk=userid)
        booking = Bookings.objects.all()
        return render(request, 'scheduler/availableslots.html',
                      {'user': user, 'booking': booking})
    else:
        return render(request, 'scheduler/home.html')


def register(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = User()
            user.user_fname = form.cleaned_data['fname'].strip()
            user.user_lname = form.cleaned_data['lname'].strip()
            user.user_email = form.cleaned_data['email'].strip()
            user.user_password = form.cleaned_data['password'].strip()
            user.save()
            return HttpResponseRedirect(reverse('scheduler:login'))
    elif 'user_id' in request.session:
        return HttpResponseRedirect(reverse('scheduler:index'))
    else:
        form = SignupForm()

    return render(request, 'scheduler/register.html', {'form': form})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            user = User.objects.get(user_email=request.POST['username'])
            request.session['user_id'] = user.id
            return HttpResponseRedirect(reverse('scheduler:index'))
    elif 'user_id' in request.session:
        return HttpResponseRedirect(reverse('scheduler:index'))
    else:
        form = LoginForm()
    return render(request, 'scheduler/login.html', {'form': form})


def logout(request):
    try:
        del request.session['user_id']
    except KeyError:
        pass
    return HttpResponseRedirect(reverse('scheduler:index'))


def book_slot(request):
    if request.method == 'POST':
        time = request.POST.get('drpdwntime')
        date = request.POST.get('drpdwndate')
        print(time)
        userid = request.session['user_id']
        user = User.objects.get(pk=userid)
        usermail = user.user_email
        username= user.user_fname
        try:
            booking = Bookings.objects.get(client_email=usermail)
        except Bookings.DoesNotExist:
            bookings = Bookings()
            bookings.client_email = usermail
            bookings.client_name = username
            ls = time.split("-")
            bookings.slot_time = ls[0]
            bookings.slot_date = date

            bookings.slot_end_time = ls[1]
            bookings.save()
            return render(request, 'scheduler/abc.html', {'bookings': bookings})
        return render(request, 'scheduler/abc.html', {'booking': booking})
    else:
        return HttpResponseRedirect(reverse('scheduler:index'))


def create_event(request):

    if request.method == 'POST':
    # print(request.POST.get('abc@gmail.com'))
        clientname = request.POST.get('drpdwndate')
        if request.POST.get('accept'):

            booking = Bookings.objects.get(client_email=clientname)
            date = booking.slot_date
            start_time = booking.slot_time
            end_time = booking.slot_end_time
            booking.is_scheduled = True
            booking.save()
            # userid = request.session['user_id']
            # user = User.objects.get(pk=userid)
            service = create_service()
            # start_datetime = datetime.datetime.now(tz=pytz.utc)
            f = "%Y-%m-%d %H:%M"
            startdatestring1 = date + " " + start_time
            startdatestring2 = date + " " + end_time
            sf_timezone = pytz.timezone('Asia/Kolkata')

            start_datetime = datetime.datetime.strptime(startdatestring1, f).astimezone(sf_timezone)
            end_datetime = datetime.datetime.strptime(startdatestring2, f).astimezone(sf_timezone)
            event = service.events().insert(calendarId='primary', body={
                'summary': 'Meeting with ' + booking.client_name,
                'description': 'Created using scheduler app',
                'start': {'dateTime': (start_datetime+timedelta(hours=12)).isoformat()},
                'end': {'dateTime': (end_datetime+timedelta(hours=12)).isoformat()},
            }).execute()
            return render(request, 'scheduler/successfulschedule.html', {'booking': booking})
        elif request.POST.get('reject'):
            booking = Bookings.objects.get(client_email=clientname)
            booking.delete()
            return render(request, 'scheduler/successfulschedule.html', {'clientname': clientname})
    else:
        return HttpResponseRedirect(reverse('scheduler:index'))

    
def create_service():
    store = file.Storage('token.json')
    creds = store.get()
    if not creds or creds.invalid:
        flow = client.flow_from_clientsecrets('credentials.json', SCOPES)
        creds = tools.run_flow(flow, store)
    service = build('calendar', 'v3', http=creds.authorize(Http()))
    return service

scheduler/templates/scheduler/abc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if booking%}
<h2>You have <i style="color:red">already</i> booked an appointment slot of <i style="color:green">{{booking.slot_time}}</i> to <i style="color:green">{{booking.slot_end_time}}</i> on date {{booking.slot_date}}</h2>
{% else %}
<h2>You have booked an appointment slot of <i style="color:green">{{bookings.slot_time}}</i> to <i style="color:green">{{bookings.slot_end_time}}</i> on date {{bookings.slot_date}}</h2>
{% endif %}
</body>
</html>

scheduler/templates/scheduler/availableslots.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 15px;
}
</style>
<body>
{% if user.user_email == 'mockersage9@gmail.com' %}
<div style="float:left">
    <h2 style="margin-left:40px">Hi, {{user.user_fname}}</h2>
</div>
<div style="float:right">
    <h2 style="margin-right:40px" ><a href="{% url 'scheduler:logout' %}">Logout</a></h2>
</div>
<table style="width:100%">
    <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Date</th>
    <th>Start Time</th>
    <th>End Time</th>
    <th>schedule</th>
        <th>Reject</th>
  </tr>
    {% for boo in booking %}
    {% if not boo.is_scheduled and not boo.client_email == 'mockersage9@gmail.com' %}
  <form method="post" action="{% url 'scheduler:create_event' %}">
    {% csrf_token %}
    <tr>
      <td>{{boo.client_name}}</td>
      <!--<td><input type="hidden" id="abc" name="abc" value="abc">{{boo.client_email}}</td>-->
    <td>
        <select name="drpdwndate">

            <option>{{boo.client_email}}</option>
        </select></td>
        <td>{{boo.slot_date}}</td>
    <td>{{boo.slot_time}}</td>
      <td>{{boo.slot_end_time}}</td>
        <td><input type="submit" name="accept" align="middle" value="Schedule"> </td>
        <td><input type="submit" name="reject" align="middle" value="Reject"> </td>
  </tr>
      </form>
    {% endif %}
    {% endfor %}
</table>


{% else %}
<div style="float:left">
    <h2 style="margin-left:40px">Hi, {{user.user_email}}</h2>
    <div style="text-align:center">
        <h2 style="color:red">(Mr. X's calendar)</h2>
            <iframe src="https://calendar.google.com/calendar/embed?src=mockersage9%40gmail.com&ctz=Asia%2FCalcutta" style="border: 0" width="900" height="600" frameborder="0" scrolling="no"></iframe>
    </div>
    </div>
<div style="float:right">
    <h2 style="margin-right:40px" ><a href="{% url 'scheduler:logout' %}">Logout</a></h2>
    <h3 style="text-align:center;margin-top:60px;margin-right:50px">Schedule your time</h3>
    <form method="post"  style="margin-top:30px" action="{% url 'scheduler:book_slot' %}">
        {% csrf_token %}
        <select name="drpdwndate">

            <option>2018-08-22</option>
            <option>2018-08-30</option>
            <option>2018-09-09</option>
        </select>
        <select name="drpdwntime">

            <option>1:00-2:30</option>
            <option>2:00-2:30</option>
            <option>11:00-12:30</option>
        </select>

    <input type="submit" value="submit">

    </form>
</div>

{% endif %}
</body>
</html>

scheduler/templates/scheduler/home.html
<html>
<body>

<h1 style="color:red;text-align:center">Welocome to Meeting Scheduler</h1>

<div style="text-align:center;padding-top:140px">
<p style="font-size:40px"><a href="{% url 'scheduler:register' %}">Register</a></p>
</div>
<div style="text-align:center;">
<p style="font-size:40px"><a href="{% url 'scheduler:login' %}">Login</a></p>
</div>
</body>
</html>

scheduler/templates/scheduler/login.html
<html>
<body>
<div action="" style="text-align:center;padding-top:180px">
     <h1 style="padding-bottom:50px">Login </h1>
<form method="post">
{% csrf_token %}
     {{ form }}
<input type="submit" value="Login" />
</form>
</div>
</body>
</html>

scheduler/templates/scheduler/register.html
<html>
<body>
<div action="" style="text-align:center;padding-top:200px">
<form method="post">
{% csrf_token %}
     {{ form }}
<input type="submit" value="Register" />
</form>
</div>
</body>
</html>

scheduler/templates/scheduler/successfulschedule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% if booking %}
<h2>You have scheduled meeting with {{booking.client_name }}</h2>
<h2><a href="{% url 'scheduler:index' %}">Go Back </a></h2>
{% elif clientname %}
<h2>You have cancelled meeting with {{clientname }}</h2>
<h2><a href="{% url 'scheduler:index' %}">Go Back </a></h2>
{% endif %}
</body>
</html>